# CircleCI Firebase Deployment Config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "gatsby/package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
            - gatsby-cache-
      - run:
          name: Install Dependencies
          command: |
            cd  ~/build/gatsby
            npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "gatsby/package-lock.json" }}
          paths:
            - gatsby/node_modules
      - save_cache:
          key: gatsby-cache-{{ epoch }}
          paths:
            - gatsby/.cache
      - run:
          name: Gatsby Build
          command: |
            cd  ~/build/gatsby
            npm run build
      - run:
          name: Firebase Deploy
          command: ~/build/gatsby/node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"